services:
  - type: web
    name: worldbase-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.19
      - key: VITE_API_URL
        value: https://worldbase-server.onrender.com
